name: hector_nbb
description: "Hybrid human-AI anti-diet coaching app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  cloud_functions: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_analytics: ^12.0.1
  flutter_riverpod: ^3.0.0
  hooks_riverpod: ^3.0.0
  flutter_hooks: ^0.21.3+1
  go_router: ^16.2.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_markdown: ^0.7.7+1
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_native_splash:
  color: "#000000"            # Fondo del splash (puedes cambiar el color)
  image: assets/HectorNBB.png # Tu logo
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true

  # Ícono base (PNG cuadrado, ideal 1024x1024)
  image_path: "assets/HectorNBB.png"

  # Ícono adaptativo (Android 8+ / 12+)
  adaptive_icon_foreground: "assets/HectorNBB.png"
  adaptive_icon_background: "#000000"

  # iOS: elimina canal alfa para evitar rechazo
  remove_alpha_ios: true