// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPMZWh-NWlTDyojH8Y-TVSuUIoN8-ifU',
    appId: '1:417167835751:web:312921aa29cf044004cac2',
    messagingSenderId: '417167835751',
    projectId: 'hector-nbb',
    authDomain: 'hector-nbb.firebaseapp.com',
    storageBucket: 'hector-nbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXJvEcisUpl4SeoqChwN2mtDdRmA3OXr8',
    appId: '1:417167835751:android:6c7ae3eefda2baff04cac2',
    messagingSenderId: '417167835751',
    projectId: 'hector-nbb',
    storageBucket: 'hector-nbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMyPeYG2HqovMHno61iO5xoATVMPxlZig',
    appId: '1:417167835751:ios:ac868100145929bc04cac2',
    messagingSenderId: '417167835751',
    projectId: 'hector-nbb',
    storageBucket: 'hector-nbb.firebasestorage.app',
    iosBundleId: 'com.example.hectorNbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMyPeYG2HqovMHno61iO5xoATVMPxlZig',
    appId: '1:417167835751:ios:ac868100145929bc04cac2',
    messagingSenderId: '417167835751',
    projectId: 'hector-nbb',
    storageBucket: 'hector-nbb.firebasestorage.app',
    iosBundleId: 'com.example.hectorNbb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtPMZWh-NWlTDyojH8Y-TVSuUIoN8-ifU',
    appId: '1:417167835751:web:9ab3f86fd4170d9f04cac2',
    messagingSenderId: '417167835751',
    projectId: 'hector-nbb',
    authDomain: 'hector-nbb.firebaseapp.com',
    storageBucket: 'hector-nbb.firebasestorage.app',
  );

}